DROP TABLE IF EXISTS `TRANSLATION`;
DROP TABLE IF EXISTS `TRANSLATION_DICTIONNARY`;
DROP TABLE IF EXISTS `LANGUAGE`;
DROP TABLE IF EXISTS `VEHICLE_PRESENTATION`;
ALTER TABLE `USER` DROP FOREIGN KEY FK_UserLicence;
DROP TABLE IF EXISTS `LICENCE`;
DROP TABLE IF EXISTS `RESERVATION`;
DROP TABLE IF EXISTS `PAYMENT_STATUS`;
DROP TABLE IF EXISTS `PICTURE`;
DROP TABLE IF EXISTS `PICTURE_TYPE`;
DROP TABLE IF EXISTS `MESSAGE`;
DROP TABLE IF EXISTS `CONVERSATION`;
DROP TABLE IF EXISTS `OFFER`;
DROP TABLE IF EXISTS `AGENCY`;
DROP TABLE IF EXISTS `VEHICLE`;
DROP TABLE IF EXISTS `USER`;
DROP TABLE IF EXISTS `USER_ROLE`;
DROP TABLE IF EXISTS `CREDIT_CARD`;
DROP TABLE IF EXISTS `ADDRESS`;

CREATE TABLE IF NOT EXISTS `ADDRESS` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `street_number` INTEGER NOT NULL,
  `street_name` VARCHAR(500) NOT NULL,
  `postcode` INTEGER NOT NULL,
  `locality_name` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `CREDIT_CARD` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cb_number` VARCHAR(16) NOT NULL,
  `expiration_date` DATE NOT NULL,
  `crypto_code` VARCHAR(3) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `USER_ROLE` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE (`name`)
);

CREATE TABLE IF NOT EXISTS `USER` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `birth_date` DATE NOT NULL,
  `phone_number` VARCHAR(10),
  `role_id` BIGINT NOT NULL,
  `address_id` BIGINT NOT NULL,
  `credit_card_id` BIGINT,
  `licence_id` BIGINT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`address_id`) REFERENCES `ADDRESS`(`id`),
  FOREIGN KEY (`credit_card_id`) REFERENCES `CREDIT_CARD`(`id`),
  FOREIGN KEY (`role_id`) REFERENCES `USER_ROLE`(`id`),
  UNIQUE (`email`)
);

CREATE TABLE IF NOT EXISTS `VEHICLE` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `number_plate` VARCHAR(15) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `mileage` FLOAT NOT NULL,
  `condition` VARCHAR(255) NOT NULL,
  `number_of_door` INTEGER NOT NULL,
  `transmission` VARCHAR(255) NOT NULL,
  `fuel` VARCHAR(255) NOT NULL,
  `transport_capacity` FLOAT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE (`number_plate`)
);

CREATE TABLE IF NOT EXISTS `AGENCY` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(10) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `address_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`address_id`) REFERENCES `ADDRESS`(`id`)
);

CREATE TABLE IF NOT EXISTS `OFFER` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `depart_date` DATETIME NOT NULL,
  `arrival_date` DATETIME NOT NULL,
  `tarif` FLOAT NOT NULL,
  `depart_agency_id` BIGINT NOT NULL,
  `arrival_agency_id` BIGINT NOT NULL,
  `vehicle_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`vehicle_id`) REFERENCES `VEHICLE`(`id`),
  FOREIGN KEY (`depart_agency_id`) REFERENCES `AGENCY`(`id`),
  FOREIGN KEY (`arrival_agency_id`) REFERENCES `AGENCY`(`id`)
);

CREATE TABLE IF NOT EXISTS `MESSAGE_TYPE` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE (`name`)
);

CREATE TABLE IF NOT EXISTS `MESSAGE` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(255),
  `text` TEXT NOT NULL,
  `type_id` BIGINT NOT NULL,
  `is_read` BOOLEAN NOT NULL,
  `sender_id` BIGINT NOT NULL,
  `receiver_id` BIGINT NOT NULL,
  `message_parent_id` BIGINT NULL DEFAULT NULL,
  `is_parent` INT(1) GENERATED ALWAYS AS (IF(`message_parent_id` IS NULL,  1, NULL)) VIRTUAL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`sender_id`) REFERENCES `USER`(`id`),
  FOREIGN KEY (`receiver_id`) REFERENCES `USER`(`id`),
  FOREIGN KEY (`message_parent_id`) REFERENCES `MESSAGE`(`id`),
  FOREIGN KEY (`type_id`) REFERENCES `MESSAGE_TYPE`(`id`),
  CONSTRAINT UC_MessageRoot UNIQUE (`type_id`, `sender_id`, `receiver_id`, `is_parent`),
  CONSTRAINT UC_MessageChild UNIQUE (`type_id`, `sender_id`, `receiver_id`, `message_parent_id`)
);

CREATE TABLE IF NOT EXISTS `PICTURE_TYPE` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE (`name`)
);

CREATE TABLE IF NOT EXISTS `PICTURE` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `blob` LONGBLOB NOT NULL,
  `size` INTEGER NOT NULL,
  `type_id` BIGINT NOT NULL,
  `vehicle_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`type_id`) REFERENCES `PICTURE_TYPE`(`id`),
  FOREIGN KEY (`vehicle_id`) REFERENCES `VEHICLE`(`id`)
);

CREATE TABLE IF NOT EXISTS `PAYMENT_STATUS` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE (`name`)
);

CREATE TABLE IF NOT EXISTS `RESERVATION` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `reservation_date` DATETIME NOT NULL,
  `payment_status_id` BIGINT,
  `user_id` BIGINT NOT NULL,
  `offer_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`payment_status_id`) REFERENCES `PAYMENT_STATUS`(`id`),
  FOREIGN KEY (`user_id`) REFERENCES `USER`(`id`),
  FOREIGN KEY (`offer_id`) REFERENCES `OFFER`(`id`)
);

CREATE TABLE IF NOT EXISTS `LICENCE` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `picture_id` BIGINT NOT NULL,
  `reservation_id` BIGINT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`picture_id`) REFERENCES `PICTURE`(`id`),
  FOREIGN KEY (`reservation_id`) REFERENCES `RESERVATION`(`id`)
);

CREATE TABLE IF NOT EXISTS `VEHICLE_PRESENTATION` (
  `vehicle_id` BIGINT NOT NULL,
  `picture_id` BIGINT NOT NULL,
  PRIMARY KEY (`vehicle_id`, `picture_id`),
  FOREIGN KEY (`vehicle_id`) REFERENCES `VEHICLE`(`id`),
  FOREIGN KEY (`picture_id`) REFERENCES `PICTURE`(`id`)
);

CREATE TABLE IF NOT EXISTS `LANGUAGE` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `language_code` VARCHAR(5) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `culture_code` VARCHAR(5) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `TRANSLATION_DICTIONNARY` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE (`key`)
);

CREATE TABLE IF NOT EXISTS `TRANSLATION` (
  `language_id` BIGINT NOT NULL,
  `translation_dictionnary_id` BIGINT NOT NULL,
  `text` TEXT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`language_id`) REFERENCES `LANGUAGE`(`id`),
  FOREIGN KEY (`translation_dictionnary_id`) REFERENCES `TRANSLATION_DICTIONNARY`(`id`),
  PRIMARY KEY (`language_id`, `translation_dictionnary_id`)
);

ALTER TABLE `USER` ADD CONSTRAINT FK_UserLicence FOREIGN KEY (`licence_id`) REFERENCES `LICENCE`(`id`);

INSERT INTO ADDRESS (street_number, street_name, locality_name, postcode, country) VALUES ('5', 'Rue des fougère', 'Bourges', 18033, 'France');
INSERT INTO ADDRESS (street_number, street_name, locality_name, postcode, country) VALUES ('104', 'Rue des thons', 'Nantes', 44000, 'France');
INSERT INTO USER_ROLE (name) VALUES ('CLIENT');
INSERT INTO USER_ROLE (name) VALUES ('SUPPORT');
INSERT INTO PICTURE_TYPE (name) VALUES ('PNG');
INSERT INTO PICTURE_TYPE (name) VALUES ('JPEG');
INSERT INTO PAYMENT_STATUS (name) VALUES ('REFUSED');
INSERT INTO PAYMENT_STATUS (name) VALUES ('ACCEPTED');
INSERT INTO PAYMENT_STATUS (name) VALUES ('ONGOING');
INSERT INTO MESSAGE_TYPE (name) VALUES ('CHAT');
INSERT INTO MESSAGE_TYPE (name) VALUES ('MAIL');
INSERT INTO USER (email, password, lastname, firstname, birth_date, address_id, role_id) VALUES ('client1@test.com', '$2a$10$J9eBtaA7YouyzXa2ipe7wOQ2OQyvV1XYaXZDDW3dCAykAvXWnQfQO', '1', 'client', '1995-05-25', '1', '1');
INSERT INTO USER (email, password, lastname, firstname, birth_date, address_id, role_id) VALUES ('client2@test.com', '$2a$10$h.jamLfMDC5ar5E2KV8XO.njNtoNH.1U6.lBOYow7EYLNKhwUpDwi', '2', 'client', '1995-05-25', '2', '1');
INSERT INTO USER (email, password, lastname, firstname, birth_date, address_id, role_id) VALUES ('support1@test.com', '$2a$10$ollBOaCt56GWOX7.UlkfMu8L/rsx9fdw6UjxFh5jT7ukHPsA4RbAW', '1', 'support', '2000-10-07', '1', '2');


